Vagrant.configure("2") do |config|
  config.vm.define vm_name = "web" do |web|
    web.vm.hostname = "#{vm_name}"
    web.vm.provider "docker" do |d|
      d.force_host_vm = true
      d.vagrant_vagrantfile = "../Vagrantfile"
      d.vagrant_machine = "dockerhost"
      d.build_dir = "trusty-php5info-web"
      d.has_ssh = false
      d.ports = ["8080:80"]
    end
  end
end
